name: benchmark
on:
  push:
    branches:
      - main  #any push to main branch triggers this workflow
    paths-ignore:
      - 'benchmarks/asv/html/**' #THIS MAKES IT SO THE PUSH AT THE END DOES NOT RETRIGGER
  workflow_dispatch:
  # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  benchmark:
    runs-on: ubuntu-latest  
    timeout-minutes: 120  #times out after 2 hours
    defaults: 
      run: 
        working-directory: ./benchmarks #sets the default working directory to ./benchmarks 
    steps:
          - uses: actions/setup-python@v5  #sets up python with version 3.12
            with:
              python-version: "3.12"
          - name: Checkout asv_results
            uses: actions/checkout@v4  #checks out repository
            with:
              fetch-depth: 0  # Fetch full history
          - name: Fetch full git history #fetches repository, including tags, for benchmarking data
            run: |
              git fetch --unshallow || true
              git fetch --all --tags --prune
              git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
              git fetch origin
          - run: git fetch origin $GITHUB_BASE_REF:base $GITHUB_REF:pr
          - name: Checkout results_asv_results
            uses: actions/checkout@v4
            with:
              repository: blue-jaye-121/results_asv_results
              persist-credentials: false
              fetch-depth: 0
              token: ${{ secrets.ASV_PAT }}
              ref: main
              path: results_asv_results

          - name: DEBUG Check contents of results_asv_results
            run: |
              echo "Listing ../results_asv_results"
              ls -l ../results_asv_results
              echo "Listing ../results_asv_results/results"
              ls -l ../results_asv_results/results || echo "No results directory found"
              ls -l ./asv/results
          - name: Copy existing results
            run: |
              if [ -d "../results_asv_results/results" ]; then
              cp -r ../results_asv_results/results/* ./asv/results
              fi
          - name: DEBUG check contents of asv/results after copyin
            run: |
              ls -l ./asv/results

          - name: Update .txt file of commits  #run the generate_hashes.sh bash script to generate the no_bot_merge_commits.txt
            run: bash generate_hashes.sh
          - uses: actions/upload-artifact@v4
            with:
              name: no_bot_merge_commits.txt  # upload the updated no_bot_merge_commits.txt file to ./benchmarks
              path: .
          - run: pip install asv virtualenv  #install asv
          - run: python -m asv machine --yes  #setup the asv machine settings with device-given defaults
          - name: Run ASV
            run: python -m asv run 31bd7351b0f54e32c7adc20e5d3dde4a4107d350^! #HASHFILE:no_bot_merge_commits.txt  # run ASV on the commits in the hashfile
            continue-on-error: true #Tells GHA that a failed benchmark is ok, continue to run
          - name: Commit and push benchmark results to results_asv_results
            run: |
              if [ -d "../results_asv_results/results" ]; then
                rm -r ../results_asv_results/results
              fi
              cp -r ./asv/results/ ../results_asv_results/results
              cd ../results_asv_results
              git config --local user.email "github-actions@github.com"
              git config --local user.name "GitHub Actions [bot]"
              git add results
              git commit -m "Update benchmark results"
        
          - name: Push to results_asv_results
            if: github.ref == 'refs/heads/main' && github.repository == 'blue-jaye-121/asv_results'
            uses: ad-m/github-push-action@77c5b412c50b723d2a4fbc6d71fb5723bcd439aa # master
            with:
              github_token: ${{ secrets.ASV_PAT }}
              branch: main
              force: true
              repository: blue-jaye-121/results_asv_results
              directory: results_asv_results

