name: benchmark
on: [push]
jobs:
  benchmark:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./benchmarks
    steps:
          - uses: actions/setup-python@v2
            with:
              python-version: "3.13"
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0  # Fetch full history
          - run: git fetch origin $GITHUB_BASE_REF:base $GITHUB_REF:pr
          - run: pip install asv virtualenv
          - run: python -m asv machine --yes
          - run: python -m asv run
          - run: python -m asv publish
          - uses: actions/upload-artifact@v4
            with:
              name: asv-results
              path: benchmarks/.asv/html
