name: benchmark
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'benchmarks/asv/html/**' #THIS MAKES IT SO THE PUSH AT THE END DOES NOT RETRIGGER
jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    defaults: 
      run: 
        working-directory: ./benchmarks
    steps:
          - uses: actions/setup-python@v2
            with:
              python-version: "3.13"
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0  # Fetch full history
          - name: Fetch full git history
            run: |
              git fetch --unshallow || true
              git fetch --all --tags --prune
              git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
              git fetch origin
          - run: git fetch origin $GITHUB_BASE_REF:base $GITHUB_REF:pr
          - run: pip install asv virtualenv
          - run: python -m asv machine --yes
          - run: python -m asv run `git log --merges v1.6.0..v1.7.0 --pretty=format:"%H %an %cn %s" | grep -v -i "dependabot" | grep -v -E "github-actions\[bot\]|dependabot\[bot\]" | awk '{print $1}'`
          - run: python -m asv publish
            working-directory: ./benchmarks
          - run: git config user.name "github-actions"
          - run: git config user.email "actions@github.com"
          - name: Commit ASV HTML to main
            run: |
              git add asv/html
              if ! git diff --cached --quiet; then
              git commit -m "Update ASV benchmark HTML"
              git push origin main
              else
              echo "No changes to commit."
              fi
